name: "🔧 refactoring"
description: "코드 리팩토링한 내용"
title : "[] "
labels: ["🔧 refactoring"]
projects: ["Pive-Guyz/2"]
body:
  - type: textarea
    attributes:
      label: 📄 설명
      description: 리팩토링한 코드에 대해 설명해주세요.
      placeholder: 최대한 자세하게 작성해주세요!
      value:
    validations:
      required: true